config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cmv.console:
      branch: main
      repo: https://github.com/cessda/cessda.cmv.console
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cmv.console git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-vermilion-mule.sh
        container: qc.acc_flabby-aquamarine-affenpinscher
  QC.Doc:
    repos:
      github.com/cessda/cessda.cmv.console find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-xanthic-seal.sh
        container: qc.doc_sleazy-cinnabar-rattlesnake
      github.com/cessda/cessda.cmv.console git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-cinnabar-duck.sh
        container: qc.doc_droopy-bronze-wombat
      github.com/cessda/cessda.cmv.console markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-apricot-meerkat.sh
        container: qc.doc_hasty-goldenrod-bombay
  QC.Lic:
    repos:
      github.com/cessda/cessda.cmv.console licensee:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-purple-bobcat.sh
        container: qc.lic_geeky-harlequin-fousek
  QC.Met:
    repos:
      github.com/cessda/cessda.cmv.console cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.homely-denim-gerbil.sh
        container: qc.met_foggy-gold-gar
  QC.Sty:
    repos:
      github.com/cessda/cessda.cmv.console checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-viridian-dollar.sh
        container: qc.sty_skimpy-jade-blue
  QC.Ver:
    repos:
      github.com/cessda/cessda.cmv.console get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-tomato-caterpillar.sh
        container: qc.ver_geeky-burgundy-fox
timeout: 5400
