config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cmv.console:
      branch: main
      repo: https://github.com/cessda/cessda.cmv.console
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cmv.console git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-red-gorilla.sh
        container: qc.acc_snoopy-thistle-husky
  QC.Doc:
    repos:
      github.com/cessda/cessda.cmv.console find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-copper-pinscher.sh
        container: qc.doc_lanky-aquamarine-fousek
      github.com/cessda/cessda.cmv.console git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-persimmon-russel.sh
        container: qc.doc_flabby-harlequin-mule
      github.com/cessda/cessda.cmv.console markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-purple-mule.sh
        container: qc.doc_ugly-maroon-terrier
  QC.Lic:
    repos:
      github.com/cessda/cessda.cmv.console licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-jade-kakapo.sh
        container: qc.lic_wheezy-mauve-angelfish
  QC.Met:
    repos:
      github.com/cessda/cessda.cmv.console cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-rust-stoat.sh
        container: qc.met_shaky-tan-dalmatian
  QC.Sty:
    repos:
      github.com/cessda/cessda.cmv.console checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-ecru-monkey.sh
        container: qc.sty_pokey-pear-iguana
  QC.Ver:
    repos:
      github.com/cessda/cessda.cmv.console get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-alizarin-turkey.sh
        container: qc.ver_foggy-eggplant-serval
timeout: 5400
