config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cmv.console:
      branch: main
      repo: https://github.com/cessda/cessda.cmv.console
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cmv.console git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-copper-frigatebird.sh
        container: qc.acc_dorky-chocolate-caiman
  QC.Doc:
    repos:
      github.com/cessda/cessda.cmv.console find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-eggplant-penguin.sh
        container: qc.doc_surly-sapphire-mongrel
      github.com/cessda/cessda.cmv.console git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-russet-quoll.sh
        container: qc.doc_hazy-turquoise-chihuahua
      github.com/cessda/cessda.cmv.console markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-celadon-stingray.sh
        container: qc.doc_paltry-seashell-russel
  QC.Lic:
    repos:
      github.com/cessda/cessda.cmv.console licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-charcoal-jackal.sh
        container: qc.lic_crabby-heliotrope-chinook
  QC.Met:
    repos:
      github.com/cessda/cessda.cmv.console cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-pumpkin-malamute.sh
        container: qc.met_snippy-gold-affenpinscher
  QC.Sty:
    repos:
      github.com/cessda/cessda.cmv.console checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-bronze-loon.sh
        container: qc.sty_homey-chocolate-civet
  QC.Ver:
    repos:
      github.com/cessda/cessda.cmv.console get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-amethyst-catfish.sh
        container: qc.ver_baggy-apricot-buzzard
timeout: 5400
